#! /bin/bash

### BEGIN INIT INFO
# Provides:             check_rs485
# Required-Start:       $remote_fs $syslog $instantiate_i2c
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    enable rs485 if jumper is set
### END INIT INFO


do_start() {
      echo -n "waiting for mcp23018"
      for check_gpio in $(seq 30)
      do
            echo -n .
            if (gpiodetect | grep -q "mcp23018")
            then
                  echo " found."
                  break
            else
                  sleep 1
            fi
      done

      if [ $(gpioget mcp23018 2) -eq 1 ]
      then
            echo "RS232 Jumper is not set, enabling RS485 mode for /dev/ttySC0"
            /usr/sbin/tty-auto-rs485 /dev/ttySC0
            exit 0
      else
            echo "RS232 Jumper is set, RS232 jumper is set, leave /dev/ttySC0 in RS232 mode."
            exit 0
      fi
}

case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  *)
        echo "Usage: check_rs485 start" >&2
        exit 3
        ;;
esac
