#! /bin/bash

### BEGIN INIT INFO
# Provides:             empc_lte
# Required-Start:       $remote_fs $syslog $instantiate_i2c
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    start empc-arpi4 lte modem
### END INIT INFO

do_start() {
        if [ $(gpioget mcp23018 10) -eq 1 ]
	then
                sleep 5
                echo "Enable power at LTE modem VBUS"
                gpioset mcp23018 5=0
                sleep 5
                echo "Pull LTE modem PWRKEY"
                gpioset mcp23018 8=0
                sleep 1
                gpioset mcp23018 8=1
                sleep 1

                # If lte modem is not yet up, check again every second up to 30 seconds
                for check_retry in $(seq 30)
                do
                        if [ $(gpioget mcp23018 10) -eq 1 ]
                        then
                                sleep 1
                        else
                                break
                        fi
                done

                if [ $(gpioget mcp23018 10) -eq 0 ]
                then

			for lsusb_check in $(seq 30)
			do
				lsusb -d "2c7c:6002" > /dev/null
				if [ $? -eq 1 ]
				then
					sleep 1
				else
					break
				fi
			done


			lsusb -d "2c7c:6002" > /dev/null
                        if [ $? -eq 1 ]
                        then
				echo "LTE USB device could not be found!"
				exit 1
			fi

                        echo "Successfully started empc-arpi4 LTE modem after $retry attempts!"

                        at_device=$(get_at_device)

                        if [ -z $at_device ]
                        then
                                echo "Could not find AT USB device, cannot enable GPS!"
                                exit 1
                        else
                                echo "Enable GPS"
                                echo "AT+QGPS=1" | socat - /dev/$at_device,crnl
                        fi

                        break
                else
                	echo "Starting empc-arpi4 LTE modem failed!"
			exit 1
                fi
        fi
}

do_stop() {
        if [ $(gpioget mcp23018 10) -eq 0 ]
        then
                echo "Stopping empc-arpi4 LTE modem!"
                gpioset mcp23018 8=0
                sleep 1
                gpioset mcp23018 8=1
                sleep 1
        fi
}

get_at_device() {
	# Find correct ttyUSB for AT Interface
        usb_tty_devs=$(readlink -f /sys/class/tty/ttyUSB*)
        for subpath in $usb_tty_devs
        do
                if (cat $subpath/../../../interface | grep -q "Mobile AT Interface")
                then
                        at_dev=$(basename $subpath)
                fi
        done
        echo $at_dev
}

case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        do_stop
        ;;
  *)
        echo "Usage: empc_lte [start|stop]" >&2
        exit 3
        ;;
esac
