#! /bin/bash

### BEGIN INIT INFO
# Provides:             instantiate_i2c
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    instantiate empc-arpi4 i2c devices
### END INIT INFO


do_start() {
        # Instatiate mcp23018 port expander i2c device
        echo mcp23018 0x20 > /sys/bus/i2c/devices/i2c-1/new_device
        # Instatiate rv8803 rtc i2c device
        echo rv8803 0x32 > /sys/bus/i2c/devices/i2c-1/new_device
}

do_stop() {
        # Delete mcp23018 port expander i2c device
        echo 0x20 > /sys/bus/i2c/devices/i2c-1/delete_device
        # Delete rv8803 rtc i2c device
        echo 0x32 > /sys/bus/i2c/devices/i2c-1/delete_device
}

case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        do_stop
        ;;
  *)
        echo "Usage: empc_lte [start|stop]" >&2
        exit 3
        ;;
esac
